#define PICTTHUMB_VER_MAJOR		1
#define PICTTHUMB_VER_MINOR		7
#define PICTTHUMB_VER_REVISION		0
#define PICTTHUMB_VER_BUILD		0

#define LOC_TX_(t) L#t

#define RC_FILE_VERSION			PICTTHUMB_VER_MAJOR,PICTTHUMB_VER_MINOR,PICTTHUMB_VER_REVISION,PICTTHUMB_VER_BUILD
#define STR_RC_FILE_VERSION		LOC_TX_(RC_FILE_VERSION)
