#ifndef APP_TYPES_H
#define APP_TYPES_H

#include "illa/types.h"

namespace App {
	enum StringID {
		SIDInvalid = 0,
		SIDLanguageName = 1,
		SIDOpen = 2,
		SIDZoom = 3,
		SIDSetWallpaper = 4,
		SIDSettings = 5,
		SIDLoadedIn = 6,
		SIDErrorLoading = 7,
		SIDSeconds = 8,
		SIDLoading = 9,
		SIDViewer = 10,
		SIDInterface = 11,
		SIDBackgroundColor = 12,
		SIDLanguage = 13,
		SIDControls = 14,
		SIDAdvanced = 15,
		SIDFiletypes = 16,
		SIDCache = 17,
		SIDAbout = 18,
		SIDMenuRename = 19,
		SIDMenuZoomIn = 20,
		SIDMenuZoomOut = 21,
		SIDZoomFitImage = 22,
		SIDZoomFullSize = 23,
		SIDZoomIn = 24,
		SIDZoomOut = 25,
		SIDWPStretch = 26,
		SIDWPCenter = 27,
		SIDWPTile = 28,
		SIDOpenDirectory = 29,
		SIDAboutFreeware = 30,
		SIDAboutLibJpeg = 31,
		SIDAboutLibPng = 32,
		SIDGroupMagnification = 33,
		SIDGroupMinification = 34,
		SIDGroupViewer = 35,
		SIDWrapAround = 36,
		SIDResetZoom = 37,
		SIDResetPan = 38,
		SIDResizeWindow = 39,
		SIDWindowCenterScreen = 40,
		SIDWindowCenterCurrent = 41,
		SIDWindowNoReposition = 42,
		SIDFilterNearestNeighbor = 43,
		SIDFilterBilinear = 44,
		SIDFilterLanczos3 = 45,
		SIDGroupPreview = 46,
		SIDGroupRGB = 47,
		SIDGroupHLS = 48,
		SIDSatSlider = 49,
		SIDR = 50,
		SIDG = 51,
		SIDB = 52,
		SIDH = 53,
		SIDL = 54,
		SIDS = 55,
		SIDMultiInstance = 56,
		SIDGroupCache = 57,
		SIDAutoMemLimit = 58,
		SIDGBytes = 59,
		SIDMBytes = 60,
		SIDKBytes = 61,
		SIDBytes = 62,
		SIDGroupClick = 63,
		SIDGroupDoubleClick = 64,
		SIDGroupMouseWheel = 65,
		SIDCtrlMouseLClick = 66,
		SIDCtrlMouseMClick = 67,
		SIDCtrlMouseRClick = 68,
		SIDCtrlMouseLDoubleClick = 69,
		SIDCtrlMouseMDoubleClick = 70,
		SIDCtrlMouseRDoubleClick = 71,
		SIDCtrlMouseWheelUp = 72,
		SIDCtrlMouseWheelDown = 73,
		SIDActionDisable = 74,
		SIDActionPan = 75,
		SIDActionContextMenu = 76,
		SIDActionToggleFullSizeDefaultZoom = 77,
		SIDActionFullscreen = 78,
		SIDActionNextImage = 79,
		SIDActionPrevImage = 80,
		SIDActionZoomIn = 81,
		SIDActionZoomOut = 82,
		SIDOpenFile = 83,
		SIDOK = 84,
		SIDCancel = 85,
		SIDClose = 86,
		SIDApply = 87,
		SIDSettingsWindow = 88,
		SIDAllImages = 89,
		SIDAdjust = 90,
		SIDGroupBrightness = 91,
		SIDGroupContrast = 92,
		SIDGroupGamma = 93,
		SIDAutoProof = 94,
		SIDDefault = 95,
		SIDGroupRM = 96,
		SIDRMBoth = 97,
		SIDRMReduceOnly = 98,
		SIDRMEnlargeOnly = 99,
		SIDGroupZM = 100,
		SIDGroupStatusBar = 101,
		SIDShowStatusBar = 102,
		SIDAlwaysOnTop = 103,
		SIDOrientation = 104,
		SIDOrientationDefault = 105,
		SIDOrientationFlipX = 106,
		SIDOrientationFlipY = 107,
		SIDOrientation90 = 108,
		SIDOrientation180 = 109,
		SIDOrientation270 = 110,
		SIDGroupFileTypes = 111,
		SIDTypeName = 112,
		SIDTypeExtension = 113,
		SIDRenameWindow = 114,
		SIDRenameFilename = 115,
		SIDRenameInvalid = 116,
		SIDNumericalInvalid = 117,
		SIDNext = 118,
		SIDPrevious = 119,
		SIDFinish = 120,
		SIDInstallWindow = 121,
		SIDInstallLanguageDesc = 122,
		SIDInstallFormatsDesc = 123,
		SIDInstallFormatsAll = 124,
		SIDInstallFormatsNoChange = 125,
		SIDInstallFormatsCustom = 126,
		SIDInstallCustomFormatsDesc = 127,
		SIDCriticalError = 128,
		SIDRenderer = 129,
		SIDRendererGDI = 130,
		SIDRendererD3D = 131,
		SIDRendererRestart = 132,
		SIDMenuSort = 133,
		SIDMenuSortFilename = 134,
		SIDMenuSortDateCreated = 135,
		SIDMenuSortDateAccessed = 136,
		SIDMenuSortDateModified = 137,
		SIDAssociationSetup = 138,
		SIDPictusDescription = 139,
		SIDDirectXFailed = 140,
		SIDKeyboard = 141,
		SIDGroupAction = 142,
		SIDGroupAssignedShortcuts = 143,
		SIDLabelKey = 144,
		SIDAdd = 145,
		SIDUndefined = 146,
		SIDRandom = 147,
		SIDActionFirstImage = 148,
		SIDActionLastImage = 149,
		SIDActionDeleteCurrentFile = 150,
		SIDActionRecycleCurrentFile = 151,
		SIDActionRemoveCurrentImage = 152,
		SIDActionNextSkipImage = 153,
		SIDActionPrevSkipImage = 154,
		SIDActionPanUp = 155,
		SIDActionPanDown = 156,
		SIDActionPanLeft = 157,
		SIDActionPanRight = 158,
		SIDActionToggleFullScreen = 159,
		SIDZoomDefault = 160,
		SIDZoomFree = 161,
		FinalSID = 162
	};

	enum ResizeBehaviour {
		ResizeEnlargeOrReduce = 0,
		ResizeEnlargeOnly,
		ResizeReduceOnly
	};

	enum ZoomMode {
		ZoomFree = 0,
		ZoomFitImage,
		ZoomFullSize,
	};

	enum ViewerAppMessage {
		ViewerImageLoadEvent = 1,
//		ViewerSettingsChanged,
		ViewerListUpdate,
	};

	enum class KeyAction {
		Undefined = 0,
		NextImage = 1,
		NextSkipImage = 2,
		PreviousImage = 3,
		PreviousSkipImage = 4,
		RenameFile = 5,
		RandomImage = 6,
		ZoomIn = 7,
		ZoomOut = 8,
		ZoomDefault = 9,
		ZoomFull = 10,
		ZoomFree = 11,
		PanUp = 12,
		PanDown = 13,
		PanLeft = 14,
		PanRight = 15,
		FirstImage = 16,
		LastImage = 17,
		RecycleCurrentFile = 18,  // Send file to recycle bin OR delete, with out without confirmation dialog, depending on OS settings.
		DeleteCurrentFile = 19,   // Immediately deletes the file, bypassing any recycle bin.
		RemoveCurrentImage = 19,  // Removes image from rotation, does NOT touch the actual file.
		ToggleFullscreen = 20,
		CloseApplication = 21,
		OpenSettings = 22
	};

	struct KeyboardPress {
		wchar_t Key;
		bool Alt;
		bool Shift;
		bool Ctrl;
	};

	StringID KeyActionSid(KeyAction action);

	std::string KeyActionToIdentifier(KeyAction action);
	KeyAction IdentifierToKeyAction(std::string identifier);

	std::wstring GetKeyString(wchar_t key);
}

#endif
