//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res_viewer.rc
//
#define IDI_APP_MAIN                    5
#define IDD_ADJUST                      119
#define IDD_RENAME                      120
#define IDI_DOCUMENT                    123
#define IDC_CURSOR_PAN2                 124
#define IDD_INSTALL                     125
#define IDD_INSTALL_LANGUAGE            126
#define IDD_INSTALL_FORMATS             127
#define IDD_INSTALL_CUSTOMFORMATS       128
#define IDB_THUMBTOOLBAR                133
#define IDC_SLIDER_ADJUST_BRIGHTNESS    1002
#define IDC_GROUP_ADJUST_BRIGHTNESS     1003
#define IDC_GROUP_ADJUST_CONTRAST       1004
#define IDC_SLIDER_ADJUST_CONTRAST      1005
#define IDC_CHECK_ADJUST_AUTOPROOF      1006
#define IDC_GROUP_ADJUST_GAMMA          1007
#define IDC_SLIDER_ADJUST_GAMMA         1008
#define IDC_BUTTON_ADJUST_DEFAULT       1009
#define IDC_BUTTON_ADJUST_APPLY         1010
#define IDC_BUTTON_ADJUST_CLOSE         1011
#define IDC_EDIT_RENAME_NAME            1012
#define IDC_TEXT_RENAME_FILENAME        1013
#define IDC_BUTTON_INSTALL_NEXT         1015
#define IDC_BUTTON_INSTALL_PREVIOUS     1016
#define IDC_STATIC_INSTALL_LANGUAGE_DESC 1017
#define IDC_COMBO_INSTALL_LANGUAGE_LANG 1018
#define IDC_STATIC_INSTALL_FORMATS_DESC 1019
#define IDC_RADIO_INSTALL_FORMATS_ALLFORMATS 1020
#define IDC_RADIO_INSTALL_FORMATS_NOCHANGE 1022
#define IDC_RADIO_INSTALL_FORMATS_CUSTOM 1024
#define IDC_STATIC_INSTALL_CUSTOMFORMATS_DESC 1025
#define IDC_LIST_INSTALL_CUSTOMFORMATS_FILEFORMATS 1026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
